services:
  nginx:
    image: nginx
    ports:
      - "9002:9002"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./php:/usr/share/nginx/php
    depends_on:
      - php
    networks:
      - app_network
    command: ["nginx", "-g", "daemon off;"] # Запуск Nginx в foreground

  php:
    build: ./php
    image: php:7.4-fpm
    volumes:
      - ./php:/var/www/php
    networks:
      - app_network
    ports:
      - "8000:8000"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Установите пароль для root
      MYSQL_DATABASE: my_database # Установите имя базы данных
    volumes:
      - db_data:/var/lib/mysql # Именованный volume для базы данных
    networks:
      - app_network
    ports:
      - "3306:3306"

networks:
  app_network:
    driver: bridge

volumes:
  db_data: # Объявляем именованный volume
